#!/bin/bash

echo "-----------------------------"
echo " DELETE OLD THUMBNAIL"
echo "-----------------------------"
for f in *_thumb.*
do
	echo "[DELETE $f]"
	rm $f
done

echo
echo
echo "-----------------------------"
echo " UPDATE EXT TO LOWER CASE"
echo "-----------------------------"
for f in *.*
do
	ext=${f##*.}
	next=`echo $ext | tr '[:upper:]' '[:lower:]'`
	name=${f%.*}.$next
	if [ "$f" != "$name" ]; then 
		echo "[RENAME $f -> $name]"
		mv $f $name
	fi
done

echo
echo "-----------------------------"
echo " UPDATE ORIGINAL"
echo "-----------------------------"
for f in *.*
do
	or=`jhead $f | grep Orientation`
	if [ -n "$or" ]; then
		echo "[ORIENTATION $f]"
		jhead -autorot $f
	fi

	tt=`jhead $f | grep "Resolution" | xargs | sed -e 's/Resolution : //g' | sed -e 's/ x /:/g'`
	resolution=(`echo $tt | tr ':' "\n"`)
	width=${resolution[0]}
	height=${resolution[1]}
	if (( $width < $height )); then
		if (( $width > 768 )); then
			echo "[768x $f]"
			convert $f -resize '768x' $f
		else
			echo "[OKx  $f]"
		fi
	 else
		if (( $height > 768 )); then
			echo "[x768 $f]"
			convert $f -resize 'x768' $f
		else
			echo "[xOK  $f]"
		fi
	 fi
done

echo 
echo "-----------------------------"
echo " THUMBNAIL"
echo "-----------------------------"
for f in *.*
do
	n=${f%.*}_thumb.${f##*.}
	tmp=`jhead $f | grep "Resolution" | xargs | sed -e 's/Resolution : //g' | sed -e 's/ x /:/g'`
	res=(`echo $tmp | tr ':' "\n"`)
	w=${res[0]}
	h=${res[1]}
	if (( $w < $h )); then
		echo "[100x75 $n]"
		convert $f -resize '100x' -gravity center -crop 100x75+0+0 $n
	else
		echo "[75x100 $n]"
		convert $f -resize 'x75' -gravity center -crop 100x75+0+0 $n
	fi  
done
rm *t_thumb.*

